backend:
  name: git-gateway
  branch: main # or the branch you are deploying from

media_folder: "static/img" # folder where uploaded media will be stored
public_folder: "/img" # public URL for the media folder

collections:
  - name: "faq"
    label: "FAQ"
    folder: "content/faq" # folder where FAQ markdown files are stored
    create: true # allow creating new FAQ entries
    slug: "{{slug}}"
    fields:
      - { label: "Question", name: "question", widget: "string" }
      - { label: "Answer", name: "answer", widget: "markdown" }
